### ISSUE TITLE
mbedtls_aes_crypt_cbc

### ISSUE THREAD

**Issue by shiv391patel** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#108]
did all process correctly but got the following error
![image](https://user-images.githubusercontent.com/93057554/219940432-6f9014d2-7010-4c12-a227-2d6c2069ef0e.png)

**Comment by hahn23** [comment]
I think, that is maybe an issue with Whatsapp Viewer and not with the Key-Extractor itself?

I faced some strange decrypt errors also since something chanced on my system.

Try this for decrypting the database file:

https://github.com/ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter

this one worked everytime and still does perfectly.
