### ISSUE TITLE
"list of devices attached" is empty

### ISSUE THREAD

**Issue by rschuppan** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#11]
As we discussed

**Comment by YuvrajRaghuvanshiS** [comment]
[Follow conversation](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/discussions/10#discussioncomment-315248).

**Comment by YuvrajRaghuvanshiS** [comment]
I tested that but here's what happened.
Since you entered device name : 12345ab67 (say), it gets stored in memory and further down the line when program needs to run adb commands it takes that id and instead of running `adb <command>` it runs `adb -s 12345ab67 <command>`. It explicitly tells the computer to target this particular device. 
Now a point can be made what if there's only one device connected? To answer that sometimes (IDK why) it runs a new daemon of adb which does not know any previous devices and fails to run command however no matter now many times daemon run as long as device ID is explicitly told it will get the job done.

**Comment by YuvrajRaghuvanshiS** [comment]
I request you to suggest any documentation and/or program changes which make it easy to understand.

**Comment by rschuppan** [comment]
isn't this the problem? https://user-images.githubusercontent.com/31773450/106023161-d6e42880-60c6-11eb-85cc-936bdd0db839.png

**Comment by YuvrajRaghuvanshiS** [comment]
Can yur run me through the process? I mean did it ask for device id already? Any add. Info?

**Comment by rschuppan** [comment]
I didn't do anything more than what can be seen in the picture.
Just ran the script.

**Comment by YuvrajRaghuvanshiS** [comment]
You don't have to do adb devices seperately. It does this when listing device. "If list is empty close terminal, remove and replug the device, and re-run the script.
#ToDo Update README.md

**Comment by YuvrajRaghuvanshiS** [comment]
Fixed in 5e6677452de8e4d3d4f715017b3b5eeacf0d531f..b089786e50e6463938f160079e6d03d26467eb8e
