### ISSUE TITLE
Improve desecription for "reference name for this user"

### ISSUE THREAD

**Issue by 1tchy** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#54]
I was not sure what to pass under "Enter a reference name for this user". I tried varius stuff and always got a `javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption`. When I finally used my associated Gmail address as the "reference name", it worked.

I guess this was the problem, although I'm not sure. But if you think it might, maybe it could be mentioned somewhere what exactly to pass there (e.g. in the programm or also just in the readme).

**Comment by YuvrajRaghuvanshiS** [comment]
Reference name is used to get all files inside "reference name" folder in extracted folder. For ex : I enter "Yuvraj" as reference name then all my file will sit in extracted/Yuvraj folder. 
It defaults to "user" if you don't enter anything I'll add this line in code also.

Talking about the error you got that was caused because you did not provide correct password when asked. Chosen password on phone during backup creation should be same as when script asks for.

**Comment by 1tchy** [comment]
I've tried it many times and I'm pretty sure I've got the password correct at least once. And I've read somewhere else that in their method one should provide the Gmail address so I tried it and it worked. But then maybe it was just a coincidence.
Feel free to close this issue if you feel like.

**Comment by YuvrajRaghuvanshiS** [comment]
That has be coincidence. In my experience I never have faced anything like this. Also creating a folder with name something like "abc@xyz.com" would create exceptions in some OSs if anything.
