### ISSUE TITLE
"running Legacy WhatsApp for a while" unneeded and slightly misleading

### ISSUE THREAD

**Issue by vb0** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#82]
> Hit Enter key after running Legacy WhatsApp for a while. Ignore invalid date warning.  

Should be somehow rephrased as the old version by now it's just straight crashing and the user might go on the wrong track trying to actually have the old WA working when it isn't needed and in fact all is well.  

For me:  

* permissions prompt for WA comes up, I gave them all  
* I start WA it promptly closes  

I hit Enter in the script and all goes as planned. Not sure if even trying to run WA once is needed, as we need just Android to see the fact that the app allows backups (it would be good if we can avoid running the old WA altogether in case it messes up the db).  

Also if one doesn't do adb over network it would be a good idea to suggest putting the phone in airplane mode.

**Comment by YuvrajRaghuvanshiS** [comment]
The reason for running old WhatsApp for a while to get adb backup to work properly. I don't know how or why that worked but that did nevertheless.: https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/issues/16#issuecomment-776226594
This script launches WhatsApp main activity after installing its old version, that's why you get permissions prompt, so I guess that is enough to get adb backup to work properly but unfortunately I can't test it (don't use WA anymore). You can try granting permissions and don't run whatsapp and see.

>Also if one doesn't do adb over network it would be a good idea to suggest putting the phone in airplane mode.

I did see something similar on XDA a few months ago but I didn't get the significance of that. Please elaborate...

**Comment by vb0** [comment]
All right, still if it has a chance to work even if WA crashes (for me it works everywhere, including on Pixels with the latest Android) maybe just add to "running Legacy WhatsApp for a while" something like *(you might go ahead even if WA crashes, sometimes it works anyway)*. Seriously, I spent a lot of time (and messed up my WA) trying to make the old one work and then even gave up for a few months until someone told me "this really works", I was thinking I'll never make old WA work so no chance (when in fact I should've just continued and everything was fine).  

As far as going into airplane mode I think it's safer because the old WA will try to connect to their servers, you might get your account flagged or even generally there would be many more branches the software can take when connecting to a server. So basically it can either leak to them that you're doing something funny or can do something unexpected to local db/key/etc. based on some info received from the mothership. Also the behavior can be unpredictable, it can work fine for years then mess up everything for everyone due to some (intended or not) change on the server.

**Comment by YuvrajRaghuvanshiS** [comment]
Wow, I'm sorry I didn't mean to mislead. I will update that.

You're right, I can turn wifi and data off from within script. I am implementing those right away. Thanks.

**Comment by YuvrajRaghuvanshiS** [comment]
Merged to master.
