### ISSUE TITLE
invalid syntax error showing when running wa_kdbe

### ISSUE THREAD

**Issue by ShadabFaiz** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#91]
**Describe the bug**
I'm running Ubuntu 18.04.4 LTS on WSL 1.
Phone: Mi Note 10 Pro Max
Python:
``` bash
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
```

When running command `python3 wa_kdbe.py`, It is showing error
``` bash
python3 wa_kdbe.py

  File "<fstring>", line 1
    (sdk_version=)
                ^
SyntaxError: invalid syntax
```

**To Reproduce**
1. run '..'
2. Enter '..'
3. See error

**Expected behavior**
Should not throw errror

**Screenshot**
![Capture](https://user-images.githubusercontent.com/8160121/160282168-ecb0b926-c879-4f60-97ec-a1eea019d24c.PNG)

**Comment by YuvrajRaghuvanshiS** [comment]
My take on this issue is that the fstring library in Ubuntu has something to do with it.
I just ran this on Ubuntu WSL 20.04 and it seemed to work for me, try this version.

If issue persists then you will need to remove every occurrence of !s​ from lines the follow this pattern custom_print(f'I am in wakdbe.real_deal(sdk_version=!s​ ...

------- Original Message -------
