### ISSUE TITLE
code error 

### ISSUE THREAD

**Issue by fransoplo** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#98]
when i'm using the console to run wa_kdbe.py.. 
C:\Users\home\Desktop\WhatsApp-Key-Database-Extractor-master\helpers\custom_ci.py", line 37, in custom_print
    cprint(f'{time}{text_to_print}', color, attrs=attr, end=end)
NameError: name 'cprint' is not defined. Did you mean: 'print'?

How i can define cprint?

**Comment by YuvrajRaghuvanshiS** [comment]
pip install requirements.txt

**Comment by aszerman** [comment]
Trying via TCP same result:

python3 wa_kdbe.py -tip 10.10.xx.xxx -tp 5555 -s -to

First run: Auto installing python requirements.

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: packaging in /Users/java/Library/Python/3.8/lib/python/site-packages (21.3)
Requirement already satisfied: psutil in /Users/java/Library/Python/3.8/lib/python/site-packages (5.9.1)
Requirement already satisfied: termcolor in /Users/java/Library/Python/3.8/lib/python/site-packages (1.1.0)
Requirement already satisfied: requests in /Users/java/Library/Python/3.8/lib/python/site-packages (2.28.1)
Requirement already satisfied: tqdm in /Users/java/Library/Python/3.8/lib/python/site-packages (4.64.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from packaging) (3.0.9)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (1.26.6)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: termcolor in /Users/java/Library/Python/3.8/lib/python/site-packages (1.1.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: termcolor in /Users/java/Library/Python/3.8/lib/python/site-packages (1.1.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: packaging in /Users/java/Library/Python/3.8/lib/python/site-packages (21.3)
Requirement already satisfied: requests in /Users/java/Library/Python/3.8/lib/python/site-packages (2.28.1)
Requirement already satisfied: tqdm in /Users/java/Library/Python/3.8/lib/python/site-packages (4.64.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from packaging) (3.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (3.3)
* daemon not running; starting now at tcp:5037
* daemon started successfully
Traceback (most recent call last):
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/wa_kdbe.py", line 425, in <module>
    kill_me()
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/wa_kdbe.py", line 190, in kill_me
    custom_print('\n', is_get_time=False)
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/helpers/custom_ci.py", line 37, in custom_print
    cprint(f'{time}{text_to_print}', color, attrs=attr, end=end)
NameError: name 'cprint' is not defined

Thanks again!!!

**Comment by aszerman** [comment]
Hello! Thanks for reply!

I test it via USB and TCP but both got the same new error:

python3 wa_kdbe.py -ar -s -to

First run: Auto installing python requirements.

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: packaging in /Users/java/Library/Python/3.8/lib/python/site-packages (21.3)
Requirement already satisfied: psutil in /Users/java/Library/Python/3.8/lib/python/site-packages (5.9.1)
Requirement already satisfied: rich in /Users/java/Library/Python/3.8/lib/python/site-packages (12.4.4)
Requirement already satisfied: requests in /Users/java/Library/Python/3.8/lib/python/site-packages (2.28.1)
Requirement already satisfied: tqdm in /Users/java/Library/Python/3.8/lib/python/site-packages (4.64.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from packaging) (3.0.9)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (2.7.4)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (4.3.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (0.9.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (1.26.6)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/java/Library/Python/3.8/lib/python/site-packages (from requests) (2022.6.15)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rich in /Users/java/Library/Python/3.8/lib/python/site-packages (12.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (0.9.1)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (4.3.0)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/java/Library/Python/3.8/lib/python/site-packages (from rich) (2.7.4)
Traceback (most recent call last):
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/wa_kdbe.py", line 29, in <module>
    import helpers.device_serial_id as device_id
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/helpers/device_serial_id.py", line 5, in <module>
    from custom_ci import custom_input, custom_print
  File "/Users/java/Repositorios/Testing/WhatsApp-Key-Database-Extractor/helpers/custom_ci.py", line 15, in <module>
    console = Console()
NameError: name 'Console' is not defined

**Comment by YuvrajRaghuvanshiS** [comment]
Pull and try again.

-------- Original Message --------
